### ISSUE TITLE
libpython3.7m.so does not set DT_SONAME

### ISSUE THREAD

**Issue by pbienst** [codelv/conda-mobile#14]
Trying to link libpython on Android as installed through miniconda, but it doesn't link out of the box with the 'vanilla' options. Some sleuthing by Android developers turned up that this is because the python library doesn't set DT_SONAME, so that workarounds need to be used.

For more information, see here:

 https://github.com/android/ndk-samples/issues/669

**Comment by frmdstryr** [comment]
This is fixed now. Thanks!
